name: Fly Deploy
on:
  pull_request:
    types: closed

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    name: "Build api and deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Put in Datasource config
        run: |
          sed -i "s/DATABASE_URL_PLACEHOLDER/${{ secrets.DATABASE_URL }}/g" src/main/resources/applications.yml
          sed -i "s/DATABASE_USER_PLACEHOLDER/${{ secrets.DATABASE_USER }}/g" src/main/resources/applications.yml
          sed -i "s/DATABASE_PASSWORD_PLACEHOLDER/${{ secrets.DATABASE_PASSWORD }}/g" src/main/resources/applications.yml

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute Gradle build
        run: |
          chmod +x gradlew
          ./gradlew build -x test
          mv build/libs/backend-0.0.1-SNAPSHOT.jar ./backend-0.0.1-SNAPSHOT.jar

      - name: Build Docker image
        run: |
          docker build -t bobs-beagles-backend .

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}