name: Fly Deploy
on:
  pull_request:
    types: closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute Gradle build
        run: |
          ./gradlew build -x test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

      - name: Copy Jar file
        run: mv build/libs/$(ls build/libs) backend-0.0.1-SNAPSHOT.jar

      - uses: actions/upload-artifact@master
        with:
          name: jar-file
          path: backend-0.0.1-SNAPSHOT.jar

  deploy:
    name: "Deploy to fly"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@master
        with:
          name: jar-file
          path: backend-0.0.1-SNAPSHOT.jar

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}